/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "globals.hpp"
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Test_load
  (JNIEnv *, jclass, jobject instance) {
    test1(instance);
  }

#ifdef __cplusplus
}
#endif
#endif
